export const mockServices = [
  {
    id: '1',
    slug: 'web-tasarim',
    icon: '🎨',
    color: '#F5A623',
    titleTr: 'Web Tasarım',
    titleEn: 'Web Design',
    descTr: 'Kullanıcı deneyimini merkeze alan, ödül kazanan tasarımlar.',
    descEn: 'Award-winning designs that put user experience at the center.',
    features: ['UI/UX Tasarım', 'Prototipleme', 'Kullanıcı Araştırması', 'Marka Kimliği'],
    featured: true,
    published: true,
  },
  {
    id: '2',
    slug: 'web-gelistirme',
    icon: '⚡',
    color: '#6C63FF',
    titleTr: 'Web Geliştirme',
    titleEn: 'Web Development',
    descTr: 'Hız, güvenlik ve ölçeklenebilirlik odaklı modern web uygulamaları.',
    descEn: 'Modern web applications focused on speed, security, and scalability.',
    features: ['Next.js / React', 'Backend API', 'Veritabanı Tasarımı', 'DevOps'],
    featured: false,
    published: true,
  },
  {
    id: '3',
    slug: 'dijital-pazarlama',
    icon: '📈',
    color: '#10B981',
    titleTr: 'Dijital Pazarlama',
    titleEn: 'Digital Marketing',
    descTr: 'Veriye dayalı stratejilerle organik büyüme ve dönüşüm optimizasyonu.',
    descEn: 'Data-driven strategies for organic growth and conversion optimization.',
    features: ['SEO / SEM', 'İçerik Stratejisi', 'Sosyal Medya', 'E-posta Pazarlama'],
    featured: false,
    published: true,
  },
  {
    id: '4',
    slug: 'marka-kimligi',
    icon: '✦',
    color: '#F472B6',
    titleTr: 'Marka Kimliği',
    titleEn: 'Brand Identity',
    descTr: 'Akılda kalan, güçlü ve tutarlı marka deneyimleri yaratıyoruz.',
    descEn: 'We create memorable, powerful, and consistent brand experiences.',
    features: ['Logo Tasarım', 'Renk Paleti', 'Tipografi', 'Marka Rehberi'],
    featured: false,
    published: true,
  },
  {
    id: '5',
    slug: 'e-ticaret',
    icon: '🛒',
    color: '#06B6D4',
    titleTr: 'E-Ticaret',
    titleEn: 'E-Commerce',
    descTr: 'Satışlarınızı artıran yüksek dönüşümlü e-ticaret çözümleri.',
    descEn: 'High-converting e-commerce solutions that boost your sales.',
    features: ['Shopify / WooCommerce', 'Ödeme Entegrasyonu', 'Stok Yönetimi', 'Analitik'],
    featured: false,
    published: true,
  },
]

export const mockProjects = [
  {
    id: '1',
    slug: 'nova-fintech',
    titleTr: 'Nova Fintech',
    titleEn: 'Nova Fintech',
    category: 'Web',
    client: 'Nova Technologies',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80',
    tags: ['Next.js', 'Fintech', 'UI/UX'],
    featured: true,
  },
  {
    id: '2',
    slug: 'bloom-ecommerce',
    titleTr: 'Bloom E-Ticaret',
    titleEn: 'Bloom E-Commerce',
    category: 'E-Ticaret',
    client: 'Bloom Fashion',
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=80',
    tags: ['Shopify', 'Tasarım', 'SEO'],
    featured: true,
  },
  {
    id: '3',
    slug: 'pulse-sosyal',
    titleTr: 'Pulse Sosyal Medya',
    titleEn: 'Pulse Social Media',
    category: 'Sosyal Medya',
    client: 'Pulse Agency',
    image: 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=800&q=80',
    tags: ['Instagram', 'TikTok', 'İçerik'],
    featured: false,
  },
  {
    id: '4',
    slug: 'zenith-saas',
    titleTr: 'Zenith SaaS Platform',
    titleEn: 'Zenith SaaS Platform',
    category: 'Web',
    client: 'Zenith Software',
    image: 'https://images.unsplash.com/photo-1618477388954-7852f32655ec?w=800&q=80',
    tags: ['React', 'Dashboard', 'SaaS'],
    featured: false,
  },
  {
    id: '5',
    slug: 'amber-restoran',
    titleTr: 'Amber Restoran Zinciri',
    titleEn: 'Amber Restaurant Chain',
    category: 'Web',
    client: 'Amber Group',
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80',
    tags: ['Rezervasyon', 'Web', 'Tasarım'],
    featured: false,
  },
]

export const mockTestimonials = [
  {
    id: '1',
    name: 'Ahmet Yılmaz',
    role: 'CEO',
    company: 'TechStart',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&q=80',
    content: 'Mulify ile çalışmak tam anlamıyla bir dönüşüm oldu. Organik trafiğimiz 3 ayda %340 arttı.',
    rating: 5,
    metric: '+340% Trafik',
  },
  {
    id: '2',
    name: 'Zeynep Kaya',
    role: 'Marketing Director',
    company: 'Bloom Fashion',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=80&q=80',
    content: 'Yeni e-ticaret sitemiz sayesinde dönüşüm oranımız %2.1\'den %6.8\'e yükseldi. Muhteşem!',
    rating: 5,
    metric: '+224% Dönüşüm',
  },
  {
    id: '3',
    name: 'Marcus Weber',
    role: 'Founder',
    company: 'Nova Tech',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&q=80',
    content: 'The design quality and attention to detail is unmatched. Our brand is now recognized globally.',
    rating: 5,
    metric: '12 Ülke Pazarı',
  },
  {
    id: '4',
    name: 'Elif Şahin',
    role: 'Co-Founder',
    company: 'Pulse Media',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&q=80',
    content: 'Sosyal medya içerikleri ve strateji desteğiyle marka bilinirliğimiz inanılmaz yükseldi.',
    rating: 5,
    metric: '500K Yeni Takipçi',
  },
  {
    id: '5',
    name: 'Can Özdemir',
    role: 'CTO',
    company: 'Zenith Software',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&q=80',
    content: 'Next.js ile geliştirilen platformumuz mükemmel performans sergiliyor. Harika ekip!',
    rating: 5,
    metric: '98 Lighthouse Skoru',
  },
  {
    id: '6',
    name: 'Sara Johnson',
    role: 'Brand Manager',
    company: 'Global Retail',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=80&q=80',
    content: 'Our complete rebrand exceeded all expectations. Professional, creative, and on-time delivery.',
    rating: 5,
    metric: '3x Marka Değeri',
  },
]

export const mockPricingPlans = [
  {
    id: '1',
    slug: 'starter',
    nameTr: 'Başlangıç',
    nameEn: 'Starter',
    descTr: 'Küçük işletmeler ve start-up\'lar için ideal başlangıç paketi.',
    descEn: 'Ideal starter package for small businesses and start-ups.',
    monthlyPrice: 1500,
    yearlyPrice: 1200,
    currency: 'USD',
    highlighted: false,
    features: [
      '5 Sayfa Web Sitesi',
      'Responsive Tasarım',
      'SEO Temel Optimizasyon',
      '3 Ay Destek',
      'SSL Sertifikası',
      'Google Analytics',
    ],
  },
  {
    id: '2',
    slug: 'growth',
    nameTr: 'Büyüme',
    nameEn: 'Growth',
    descTr: 'Büyüyen markalar için kapsamlı dijital çözüm paketi.',
    descEn: 'Comprehensive digital solution package for growing brands.',
    monthlyPrice: 3500,
    yearlyPrice: 2800,
    currency: 'USD',
    highlighted: true,
    features: [
      '15 Sayfa Web Sitesi',
      'Özel UI/UX Tasarım',
      'Kapsamlı SEO Paketi',
      'Sosyal Medya Yönetimi',
      '6 Ay Destek & Bakım',
      'İçerik Yönetim Sistemi',
      'Performans Optimizasyonu',
      'Aylık Rapor',
    ],
  },
  {
    id: '3',
    slug: 'enterprise',
    nameTr: 'Kurumsal',
    nameEn: 'Enterprise',
    descTr: 'Büyük ölçekli markalar için sınırsız dijital çözümler.',
    descEn: 'Unlimited digital solutions for large-scale brands.',
    monthlyPrice: 0,
    yearlyPrice: 0,
    currency: 'USD',
    highlighted: false,
    features: [
      'Sınırsız Sayfa',
      'Özel Yazılım Geliştirme',
      'Dedicated Ekip',
      '7/24 Öncelikli Destek',
      'Tam Dijital Pazarlama',
      'E-Ticaret Entegrasyonu',
      'API & Sistem Entegrasyonu',
      'Aylık Strateji Toplantısı',
    ],
  },
]

export const mockFAQs = [
  {
    id: '1',
    questionTr: 'Bir proje ne kadar sürede teslim edilir?',
    questionEn: 'How long does a project take to deliver?',
    answerTr: 'Proje kapsamına göre değişmekle birlikte, standart bir web sitesi 3-6 hafta, kapsamlı dijital projeler ise 2-4 ay içinde teslim edilmektedir. İlk görüşmemizde size özel bir proje takvimi sunuyoruz.',
    answerEn: 'Depending on the project scope, a standard website takes 3-6 weeks, while comprehensive digital projects are delivered within 2-4 months. We provide a custom project timeline during our initial consultation.',
  },
  {
    id: '2',
    questionTr: 'Hangi ödeme yöntemlerini kabul ediyorsunuz?',
    questionEn: 'What payment methods do you accept?',
    answerTr: 'Banka havalesi, kredi kartı ve çeşitli uluslararası ödeme yöntemlerini kabul ediyoruz. Projeler genellikle %50 peşinat ve %50 teslimat ödemesi şeklinde yapılandırılmaktadır.',
    answerEn: 'We accept bank transfer, credit card, and various international payment methods. Projects are typically structured as 50% upfront and 50% on delivery.',
  },
  {
    id: '3',
    questionTr: 'Proje sonrası destek ve bakım sağlıyor musunuz?',
    questionEn: 'Do you provide post-project support and maintenance?',
    answerTr: 'Evet! Tüm projelerimizle birlikte belirli bir süre ücretsiz destek sunuyoruz. Uzun vadeli bakım ve güncelleme için aylık destek paketlerimiz de mevcuttur.',
    answerEn: 'Yes! All our projects come with a free support period. Monthly maintenance and update packages are also available for long-term support.',
  },
  {
    id: '4',
    questionTr: 'Projeme özel fiyat alabilir miyim?',
    questionEn: 'Can I get a custom price for my project?',
    answerTr: 'Kesinlikle! Her proje benzersizdir ve size özel bir teklif hazırlamaktan mutluluk duyarız. İletişim formumuzdan bize ulaşın, en kısa sürede detaylı bir teklif sunalım.',
    answerEn: 'Absolutely! Every project is unique and we\'d be happy to prepare a custom proposal for you. Contact us through our form and we\'ll present a detailed offer as soon as possible.',
  },
  {
    id: '5',
    questionTr: 'Hangi sektörlerde deneyiminiz var?',
    questionEn: 'What industries do you have experience in?',
    answerTr: 'Fintech, e-ticaret, sağlık, eğitim, gayrimenkul, restoran ve daha pek çok sektörde başarılı projeler gerçekleştirdik. Sektör deneyimimiz, size en doğru stratejiyi sunmamızı sağlar.',
    answerEn: 'We\'ve delivered successful projects in fintech, e-commerce, healthcare, education, real estate, restaurants, and many more sectors. Our industry experience allows us to offer you the right strategy.',
  },
]

export const mockStats = [
  { value: 150, suffix: '+', labelTr: 'Tamamlanan Proje', labelEn: 'Projects Completed' },
  { value: 98, suffix: '%', labelTr: 'Müşteri Memnuniyeti', labelEn: 'Client Satisfaction' },
  { value: 12, suffix: '+', labelTr: 'Yıllık Deneyim', labelEn: 'Years Experience' },
  { value: 40, suffix: '+', labelTr: 'Küresel Marka', labelEn: 'Global Brands' },
]

export const mockLogos = [
  { name: 'TechStart', text: 'TechStart' },
  { name: 'Bloom', text: 'Bloom' },
  { name: 'Nova', text: 'Nova' },
  { name: 'Zenith', text: 'Zenith' },
  { name: 'Pulse', text: 'Pulse' },
  { name: 'Apex', text: 'Apex' },
  { name: 'Vortex', text: 'Vortex' },
  { name: 'Nexus', text: 'Nexus' },
  { name: 'Orbit', text: 'Orbit' },
  { name: 'Fusion', text: 'Fusion' },
]
